services:
  apigateway:
    build:
      context: ./backend/ApiGateway
    ports:
      - "8080:8080"
    depends_on:
      userservice:
        condition: service_started
      appointmentservice:
        condition: service_started
      medicalrecordservice:
        condition: service_started
      notificationservice:
        condition: service_started
    networks:
      default: {}

  userservice:
    image: ${PROJECT_NAME}_user
    container_name: ${PROJECT_NAME}_user
    build:
      context: ./backend/UserService
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - postgres
      - rabbitmq
    networks:
      default: {}

  appointmentservice:
    image: ${PROJECT_NAME}_appointment
    container_name: ${PROJECT_NAME}_appointment
    build:
      context: ./backend/AppointmentService
    restart: unless-stopped
    ports:
      - 8082:8080
    depends_on:
      - postgres
      - rabbitmq
    networks:
      default: {}

  medicalrecordservice:
    image: ${PROJECT_NAME}_medicalrecord
    container_name: ${PROJECT_NAME}_medicalrecord
    build:
      context: ./backend/MedicalRecordsService
    restart: unless-stopped
    ports:
      - 8083:8080
    depends_on:
      - postgres
      - rabbitmq
      - userservice
    networks:
      default: {}

  notificationservice:
    image: ${PROJECT_NAME}_notification
    container_name: ${PROJECT_NAME}_notification
    build:
      context: ./backend/NotificationService
    restart: unless-stopped
    ports:
      - 8084:8080
    depends_on:
      - rabbitmq
    networks:
      default: {}

  postgres:
    image: postgres:14.2
    container_name: ${PROJECT_NAME}_db
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      default: {}

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"     
      - "15672:15672"   
    networks:
      default: {}

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning --requirepass P3d!sP@ssw0rd2025!
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      default: {}

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.3.2
  #   container_name: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   networks:
  #     - default

  # kafka:
  #   image: confluentinc/cp-kafka:7.3.2
  #   container_name: kafka
  #   ports:
  #     - "9092:9092"
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # Leave this as true for now
  #   healthcheck:
  #     test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "kafka:9092"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 10
  #   networks:
  #     - default

volumes:
  pgdata:
    driver: local
    name: ${PROJECT_NAME}_pgdata
  redis:
    driver: local

networks:
  default:
    driver: bridge